#!/usr/bin/env node
// Build the English trigram model the cryptanalysis uses as its fitness
// function, from this repository's own prose.
//
// A hill-climbing attack needs a way to say "this candidate plaintext is more
// English than that one", and the usual source is a downloaded corpus. This
// repository does not fetch anything at build time and does not vendor other
// people's text, so the corpus is its own: the README, the lab notes and the
// documentation, which between them are several hundred thousand letters of
// ordinary English written for this project.
//
// That is a real limitation and it is worth saying plainly. The model is
// biased towards the vocabulary of audio engineering, so it will score
// "SPECTROGRAM" more highly than a general-purpose model would and "ABDUCTED"
// less. What matters for hill climbing is the ORDER it puts candidates in, and
// ordinary English letter structure dominates any subject-matter bias at the
// trigram level. `test/cases-crypto.mjs` measures that directly: it checks the
// model separates real English from shuffled English by a wide margin on text
// this corpus has never seen.
//
//   node scripts/build-ngrams.mjs > js/crypto/trigrams.js
import { readFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

async function* walk(dir) {
  for (const e of await readdir(dir, { withFileTypes: true })) {
    if (e.name.startsWith('.') || e.name === 'node_modules') continue;
    const p = path.join(dir, e.name);
    if (e.isDirectory()) yield* walk(p);
    else yield p;
  }
}

// Prose only: fenced code, inline code, URLs and table rows are not English
// and would teach the model that HZS and PNG are common trigrams. Each source
// is stripped on its own and the results joined afterwards — stripping the
// concatenation let one unclosed fence in a document swallow everything after
// it, which took the corpus from 527,000 letters to 131,000 without a word of
// complaint.
const strip = (t) => t
  .replace(/```[\s\S]*?```/g, ' ')
  .replace(/`[^`\n]*`/g, ' ')
  .replace(/https?:\/\/\S+/g, ' ')
  .replace(/^\s*\|.*$/gm, ' ');

const pieces = [];
for await (const p of walk(path.join(ROOT, 'docs'))) if (p.endsWith('.md')) pieces.push(strip(await readFile(p, 'utf8')));
pieces.push(strip(await readFile(path.join(ROOT, 'README.md'), 'utf8')));
// The source comments too. This project's comments are written as prose — they
// argue, they cite measurements, they say what was tried and rejected — so
// they are several hundred thousand more letters of ordinary English, and
// leaving them out left two thirds of the trigrams unobserved.
for (const dir of ['js', 'workers', 'test']) {
  for await (const p of walk(path.join(ROOT, dir))) {
    if (!p.endsWith('.js') && !p.endsWith('.mjs')) continue;
    const src = await readFile(p, 'utf8');
    let text = '';
    for (const line of src.split('\n')) {
      const m = /^[ \t]*(?:\/\/|\*)[ \t]?(.*)$/.exec(line);
      if (m && !/^[ \t]*\*\//.test(line)) text += m[1] + '\n';
    }
    pieces.push(strip(text));
  }
}

const letters = pieces.join('\n').toUpperCase().replace(/[^A-Z]/g, '');
const counts = new Float64Array(26 * 26 * 26);
let total = 0;
for (let i = 0; i + 3 <= letters.length; i++) {
  const a = letters.charCodeAt(i) - 65, b = letters.charCodeAt(i + 1) - 65, c = letters.charCodeAt(i + 2) - 65;
  counts[a * 676 + b * 26 + c]++;
  total++;
}
let seen = 0;
for (let i = 0; i < counts.length; i++) if (counts[i]) seen++;

// Log probability with additive smoothing, so a trigram this corpus never saw
// still has a finite, low score rather than minus infinity — otherwise one
// unlucky trigram would veto an otherwise perfect decrypt.
const FLOOR = 0.1;
const denom = total + FLOOR * counts.length;
const logs = new Float64Array(counts.length);
let lo = Infinity, hi = -Infinity;
for (let i = 0; i < counts.length; i++) {
  logs[i] = Math.log10((counts[i] + FLOOR) / denom);
  if (logs[i] < lo) lo = logs[i];
  if (logs[i] > hi) hi = logs[i];
}
// Quantise to a byte each and pack as base64: 17,576 bytes, about 23 KB of
// source, which is the whole model.
const bytes = new Uint8Array(counts.length);
for (let i = 0; i < counts.length; i++) bytes[i] = Math.round((logs[i] - lo) / (hi - lo) * 255);
const b64 = Buffer.from(bytes).toString('base64');

process.stdout.write(`// GENERATED by scripts/build-ngrams.mjs — do not edit by hand.
//
// English letter-trigram log probabilities, from this repository's own prose:
// ${total.toLocaleString('en-US')} trigrams over ${letters.length.toLocaleString('en-US')} letters, ${seen.toLocaleString('en-US')} of the
// 17,576 possible trigrams observed. Quantised to a byte each and packed
// base64; \`SCALE\` and \`OFFSET\` put them back on a log10 scale.
//
// Additive smoothing at ${FLOOR} keeps an unseen trigram finite, so one unlucky
// trigram cannot veto an otherwise perfect decrypt.
export const TRIGRAM_COUNT = ${total};
export const TRIGRAM_LETTERS = ${letters.length};
export const TRIGRAM_SEEN = ${seen};
export const OFFSET = ${lo};
export const SCALE = ${(hi - lo) / 255};
export const PACKED = '${b64}';
`);
