#!/usr/bin/env node
// Emits the <head> loading snippet for index.html: fonts.css link, font preloads,
// one modulepreload per module in the static import graph of js/main.js
// (dependencies first), and the service-worker registration as an HTML comment.
// Dependency-free. Regenerate after any change to the import graph:
//   node scripts/gen-preload.mjs > docs/preload-snippet.html
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ENTRY = join(ROOT, 'js', 'main.js');
const FONT_DIR = join(ROOT, 'assets', 'fonts');

// Matches static `import ... from 'spec'`, bare `import 'spec'`, and
// re-exports `export ... from 'spec'`, anchored at statement start so
// dynamic import() calls never match.
const IMPORT_RE = /^\s*(?:import|export)\s+(?:[\w${},*\s]+?\s+from\s+)?['"]([^'"]+)['"]/gm;

function stripComments(src) {
  return src.replace(/\/\*[\s\S]*?\*\//g, '').replace(/^\s*\/\/.*$/gm, '');
}

function walk(file, seen, order) {
  if (seen.has(file)) return;
  seen.add(file);
  let src;
  try {
    src = readFileSync(file, 'utf8');
  } catch {
    console.error(`gen-preload: cannot read ${relative(ROOT, file)} (imported but missing)`);
    return;
  }
  const clean = stripComments(src);
  for (const match of clean.matchAll(IMPORT_RE)) {
    const spec = match[1];
    if (!spec.startsWith('./') && !spec.startsWith('../')) continue; // bare/CDN specifiers stay external
    walk(resolve(dirname(file), spec), seen, order);
  }
  order.push(file); // post-order: dependencies precede importers
}

function heaviestFonts(count) {
  return readdirSync(FONT_DIR)
    .filter((name) => name.endsWith('.woff2'))
    .map((name) => ({ name, size: statSync(join(FONT_DIR, name)).size }))
    .sort((a, b) => b.size - a.size)
    .slice(0, count);
}

const order = [];
walk(ENTRY, new Set(), order);

const lines = [];
lines.push('<!-- generated by scripts/gen-preload.mjs; paste into <head>, replacing the Google Fonts links -->');
lines.push('<link rel="stylesheet" href="assets/fonts/fonts.css">');
for (const font of heaviestFonts(2)) {
  lines.push(`<link rel="preload" href="assets/fonts/${font.name}" as="font" type="font/woff2" crossorigin>`);
}
for (const file of order) {
  lines.push(`<link rel="modulepreload" href="${relative(ROOT, file).split('\\').join('/')}">`);
}
lines.push('<!-- sw registration, paste before </body>:');
lines.push("<script>if ('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js');</script>");
lines.push('-->');

process.stdout.write(lines.join('\n') + '\n');
