// Yellowjacket Loom: deterministic binding between source material and a MIDI-
// shaped gesture. This module contains no DOM, WebAudio, or device handles.

import { studioStepDuration } from '../studio/model.js';
import { compileStudioScore } from '../studio/compile.js';
import { reidentifyLoomPlan } from './identity.js';

export {
  canonicalLoomPlanId, reidentifyLoomPlan, sameLoomPlanContent,
} from './identity.js';

export const LOOM_SCHEMA_VERSION = 3;
export const DEMO_GESTURE_STEPS = Object.freeze([0, 2, 4, 6, 8, 10, 11, 13, 14]);
export const LOOM_TRANSCRIPT_MAX_WORDS = 32;
export const LOOM_TRANSCRIPT_MAX_VOICES = 8;

export class TranscriptMaterialError extends RangeError {
  constructor(code, message, details = {}) {
    super(message);
    this.name = 'TranscriptMaterialError';
    this.code = code;
    this.details = Object.freeze({ ...details });
  }
}

function finite(value, fallback = 0) {
  const number = Number(value);
  return Number.isFinite(number) ? number : fallback;
}

function clamp(value, low, high) {
  return Math.max(low, Math.min(high, value));
}

function cleanLabel(value, fallback) {
  const label = String(value == null ? '' : value).trim();
  return label || fallback;
}

function hashText(value) {
  let hash = 0x811c9dc5;
  const text = String(value);
  for (let i = 0; i < text.length; i++) {
    hash ^= text.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193);
  }
  return (hash >>> 0).toString(16).padStart(8, '0');
}

function transcriptMaterial(entries, source) {
  const first = entries[0];
  const last = entries[entries.length - 1];
  const sourceId = cleanLabel(source.id, 'current-source');
  const id = entries.length === 1
    // Preserve the public id generated by the original one-word API.
    ? 'word-' + first.index + '-' + hashText(first.startSec + ':' + first.endSec + ':' + first.text)
    : 'phrase-' + first.index + '-' + last.index + '-' + hashText(JSON.stringify({
      sourceId,
      words: entries.map((entry) => [entry.index, entry.startSec, entry.endSec, entry.text]),
    }));
  return {
    id,
    label: entries.map((entry) => entry.label).join(' '),
    role: 'word',
    origin: {
      sourceId,
      sourceName: cleanLabel(source.name, 'SOURCE'),
      sourceSize: Number.isFinite(source.size) ? source.size : null,
      startSec: first.startSec,
      endSec: last.endSec,
      wordStart: first.index,
      wordEnd: last.index,
    },
  };
}

// For one contiguous kept-word run, find the deterministic k-phrase partition
// whose actual source spans are closest to the global target voice duration.
// Ties retain the first (earliest-boundary) candidate encountered.
function balancedRunPartition(run, groupCount, targetDuration) {
  const count = run.length;
  const table = Array.from({ length: count + 1 }, () => new Array(groupCount + 1).fill(null));
  table[0][0] = { cost: 0, ends: [] };
  for (let end = 1; end <= count; end++) {
    for (let groups = 1; groups <= Math.min(groupCount, end); groups++) {
      let best = null;
      for (let start = groups - 1; start < end; start++) {
        const previous = table[start][groups - 1];
        if (!previous) continue;
        const duration = run[end - 1].endSec - run[start].startSec;
        const error = duration - targetDuration;
        const candidate = {
          cost: previous.cost + error * error,
          ends: previous.ends.concat(end),
        };
        if (!best || candidate.cost < best.cost) best = candidate;
      }
      table[end][groups] = best;
    }
  }
  return table[count][groupCount];
}

function balancedTranscriptGroups(runs, groupCount) {
  const speechDuration = runs.reduce((total, run) => total
    + run.reduce((sum, word) => sum + (word.endSec - word.startSec), 0), 0);
  const targetDuration = speechDuration / groupCount;
  const choices = runs.map((run) => {
    const byCount = new Array(Math.min(run.length, groupCount) + 1).fill(null);
    for (let count = 1; count < byCount.length; count++) {
      byCount[count] = balancedRunPartition(run, count, targetDuration);
    }
    return byCount;
  });

  // Allocate exactly groupCount voices across hard-bounded runs while
  // minimizing the same duration objective globally. Ascending iteration plus
  // strict comparison defines deterministic tie-breaking.
  let allocations = new Array(groupCount + 1).fill(null);
  allocations[0] = { cost: 0, counts: [], partitions: [] };
  for (let runIndex = 0; runIndex < runs.length; runIndex++) {
    const next = new Array(groupCount + 1).fill(null);
    for (let used = 0; used <= groupCount; used++) {
      const prior = allocations[used];
      if (!prior) continue;
      for (let count = 1; count < choices[runIndex].length && used + count <= groupCount; count++) {
        const partition = choices[runIndex][count];
        if (!partition) continue;
        const candidate = {
          cost: prior.cost + partition.cost,
          counts: prior.counts.concat(count),
          partitions: prior.partitions.concat([partition.ends]),
        };
        const current = next[used + count];
        if (!current || candidate.cost < current.cost) next[used + count] = candidate;
      }
    }
    allocations = next;
  }

  const selected = allocations[groupCount];
  if (!selected) {
    throw new TranscriptMaterialError(
      'LOOM_TRANSCRIPT_PARTITION_FAILED',
      'LOOM COULD NOT PARTITION THE SELECTED WORDS WITHOUT CROSSING A CUT',
      { selectedCount: runs.reduce((sum, run) => sum + run.length, 0), groupCount },
    );
  }
  const groups = [];
  for (let runIndex = 0; runIndex < runs.length; runIndex++) {
    let start = 0;
    for (const end of selected.partitions[runIndex]) {
      groups.push(runs[runIndex].slice(start, end));
      start = end;
    }
  }
  return groups;
}

export function transcriptMaterials(words, i0, i1, source = {}) {
  if (!Array.isArray(words) || !words.length) return [];
  const low = Math.max(0, Math.min(i0 | 0, i1 | 0));
  const high = Math.min(words.length - 1, Math.max(i0 | 0, i1 | 0));
  const kept = [];
  const runs = [];
  let run = null;
  for (let index = low; index <= high; index++) {
    const word = words[index];
    const startSec = finite(word && word.start, -1);
    const endSec = finite(word && word.end, -1);
    if (!word || word.deleted || !(endSec > startSec)) continue;
    const entry = {
      index,
      text: word.text,
      label: cleanLabel(word.text, 'WORD ' + (index + 1)),
      startSec,
      endSec,
    };
    kept.push(entry);
    // A deleted or invalid token leaves an index gap. That gap is a hard
    // boundary: no returned source span may contain audio that was cut.
    if (!run || run[run.length - 1].index + 1 !== index) {
      run = [];
      runs.push(run);
    }
    run.push(entry);
  }

  if (kept.length > LOOM_TRANSCRIPT_MAX_WORDS) {
    throw new TranscriptMaterialError(
      'LOOM_TRANSCRIPT_WORD_LIMIT',
      'LOOM ACCEPTS AT MOST ' + LOOM_TRANSCRIPT_MAX_WORDS
        + ' KEPT WORDS (FOUND ' + kept.length + ')',
      { selectedCount: kept.length, maxWords: LOOM_TRANSCRIPT_MAX_WORDS },
    );
  }
  if (!kept.length) return [];
  // Preserve the original API byte-for-structure for selections that already
  // fit: one material per kept word, including across cuts.
  if (kept.length <= LOOM_TRANSCRIPT_MAX_VOICES) {
    return kept.map((entry) => transcriptMaterial([entry], source));
  }
  if (runs.length > LOOM_TRANSCRIPT_MAX_VOICES) {
    throw new TranscriptMaterialError(
      'LOOM_TRANSCRIPT_TOO_DISJOINT',
      'LOOM CAN WEAVE AT MOST ' + LOOM_TRANSCRIPT_MAX_VOICES
        + ' DISJOINT KEPT-WORD RUNS (FOUND ' + runs.length + ')',
      {
        selectedCount: kept.length,
        runCount: runs.length,
        maxVoices: LOOM_TRANSCRIPT_MAX_VOICES,
      },
    );
  }
  return balancedTranscriptGroups(runs, LOOM_TRANSCRIPT_MAX_VOICES)
    .map((entries) => transcriptMaterial(entries, source));
}

export function spanMaterials({ sourceId = 'current-source', sourceName = 'SOURCE', sourceSize = null,
  startSec, endSec, segments = 4, label = 'SPAN' } = {}) {
  const start = Math.max(0, finite(startSec));
  const end = Math.max(start, finite(endSec, start));
  if (!(end > start)) return [];
  const count = clamp(Math.round(finite(segments, 4)), 1, 8);
  const out = [];
  for (let index = 0; index < count; index++) {
    const a = start + (end - start) * index / count;
    const b = start + (end - start) * (index + 1) / count;
    out.push({
      id: 'span-' + hashText(sourceId + ':' + a + ':' + b),
      label: count === 1 ? cleanLabel(label, 'SPAN') : String.fromCharCode(65 + index),
      role: 'source-span',
      origin: {
        sourceId: cleanLabel(sourceId, 'current-source'),
        sourceName: cleanLabel(sourceName, 'SOURCE'),
        sourceSize: Number.isFinite(sourceSize) ? sourceSize : null,
        startSec: a,
        endSec: b,
        wordStart: null,
        wordEnd: null,
      },
    });
  }
  return out;
}

function stepStarts(bpm, swing, totalSteps = 16) {
  const out = new Array(totalSteps + 1).fill(0);
  for (let step = 0; step < totalSteps; step++) {
    out[step + 1] = out[step] + studioStepDuration(bpm, swing, step);
  }
  return out;
}

export function demoMidiGesture(bpm = 110, swing = 56) {
  const safeBpm = clamp(finite(bpm, 110), 30, 300);
  const safeSwing = clamp(finite(swing, 56), 50, 75);
  const starts = stepStarts(safeBpm, safeSwing);
  const notes = [48, 51, 55, 53, 46, 48, 51, 55, 58];
  const velocities = [0.92, 0.68, 0.82, 0.72, 0.9, 0.64, 0.76, 0.86, 0.96];
  const events = DEMO_GESTURE_STEPS.map((stepIndex, index) => ({
    eventRef: { surface: 'midi', trackId: 'demo-midi', stepIndex },
    trackIndex: 0,
    stepIndex,
    startSec: starts[stepIndex],
    durationSec: Math.max(0.08, (starts[stepIndex + 1] - starts[stepIndex]) * 0.78),
    rootNote: notes[index],
    chord: 'single',
    heardNotes: [notes[index]],
    velocity: velocities[index],
    gate: 0.78,
    audible: true,
  }));
  return {
    id: 'demo-midi-v1', kind: 'starter', label: 'STARTER GESTURE', channel: 0,
    bpm: safeBpm, swing: safeSwing, bars: 1, events,
  };
}

export function studioGesture(studio, trackIndex = 0, page = 0) {
  const track = studio && studio.tracks && studio.tracks[trackIndex];
  if (!track) return null;
  const safePage = clamp(page | 0, 0, Math.max(0, (studio.bars | 0) - 1));
  const firstStep = safePage * 16;
  const all = compileStudioScore(studio, { trackIndex });
  const selected = all.filter((event) => event.stepIndex >= firstStep && event.stepIndex < firstStep + 16);
  if (!selected.length) return null;
  let baseTime = 0;
  for (let step = 0; step < firstStep; step++) {
    baseTime += studioStepDuration(studio.bpm, studio.swing, step);
  }
  const events = selected.map((event) => ({
    ...event,
    eventRef: { ...event.eventRef, stepIndex: event.stepIndex - firstStep },
    stepIndex: event.stepIndex - firstStep,
    startSec: event.startSec - baseTime,
    writtenNote: event.rootNote,
    rootNote: Array.isArray(event.heardNotes) && Number.isFinite(event.heardNotes[0])
      ? event.heardNotes[0] : event.rootNote,
  }));
  return {
    id: 'studio-' + (track.id || trackIndex) + '-bar-' + (safePage + 1),
    kind: 'studio',
    label: 'STUDIO · ' + cleanLabel(track.name, 'TRACK ' + (trackIndex + 1)),
    channel: trackIndex,
    bpm: studio.bpm,
    swing: studio.swing,
    bars: 1,
    trackId: track.id,
    trackIndex,
    page: safePage,
    events,
  };
}

function normalizedMaterials(materials) {
  const out = [];
  const seen = new Set();
  for (const item of Array.isArray(materials) ? materials : []) {
    const origin = item && item.origin;
    const startSec = finite(origin && origin.startSec, -1);
    const endSec = finite(origin && origin.endSec, -1);
    if (!item || !origin || !(endSec > startSec)) continue;
    let id = cleanLabel(item.id, 'material-' + out.length);
    while (seen.has(id)) id += '-copy';
    seen.add(id);
    out.push({
      id,
      label: cleanLabel(item.label, 'MATERIAL ' + (out.length + 1)),
      role: cleanLabel(item.role, 'source-span'),
      origin: {
        sourceId: cleanLabel(origin.sourceId, 'current-source'),
        sourceName: cleanLabel(origin.sourceName, 'SOURCE'),
        sourceSize: Number.isFinite(origin.sourceSize) ? origin.sourceSize : null,
        startSec,
        endSec,
        wordStart: Number.isInteger(origin.wordStart) ? origin.wordStart : null,
        wordEnd: Number.isInteger(origin.wordEnd) ? origin.wordEnd : null,
      },
    });
  }
  return out;
}

export function compileLoomPlan(materials, gesture, { weaveNumber = 1, mapping = 'cycle' } = {}) {
  const clean = normalizedMaterials(materials);
  const score = gesture && Array.isArray(gesture.events)
    ? gesture.events.filter((event) => event && event.audible !== false)
      .slice().sort((a, b) => a.startSec - b.startSec || a.trackIndex - b.trackIndex)
    : [];
  if (!clean.length) throw new Error('LOOM NEEDS MATERIAL');
  if (!score.length) throw new Error('LOOM NEEDS A MIDI GESTURE');
  if (mapping !== 'cycle' && mapping !== 'zip') throw new Error('UNKNOWN LOOM MAP');

  const sortedNotes = score.map((event) => event.rootNote).sort((a, b) => a - b);
  const referenceNote = sortedNotes[Math.floor(sortedNotes.length / 2)];
  const limit = mapping === 'zip' ? Math.min(clean.length, score.length) : score.length;
  const events = [];
  const gestureKind = cleanLabel(gesture.kind,
    gesture.id === 'demo-midi-v1' ? 'starter' : 'studio');
  for (let ordinal = 0; ordinal < limit; ordinal++) {
    const gestureEvent = score[ordinal];
    const materialIndex = mapping === 'zip' ? ordinal : ordinal % clean.length;
    const material = clean[materialIndex];
    const semitones = clamp(gestureEvent.rootNote - referenceNote, -12, 12);
    const rate = Math.pow(2, semitones / 12);
    const sourceDuration = material.origin.endSec - material.origin.startSec;
    const naturalDuration = sourceDuration / rate;
    const capturedDuration = gestureKind === 'midi-capture'
      ? finite(gestureEvent.durationSec, -1) : -1;
    // MIDI capture's note-off is an audible upper bound. Encode the bound in
    // the event's actual source span so Loom audition, Machine live playback,
    // offline rendering, tail allocation, and trace all inherit one duration.
    const requestedDuration = capturedDuration > 0
      ? Math.min(naturalDuration, capturedDuration) : naturalDuration;
    const playbackEndSec = Math.min(material.origin.endSec,
      material.origin.startSec + requestedDuration * rate);
    const outputDuration = (playbackEndSec - material.origin.startSec) / rate;
    const eventSource = {
      ...material.origin,
      materialId: material.id,
      label: material.label,
    };
    if (playbackEndSec < material.origin.endSec) {
      eventSource.materialEndSec = material.origin.endSec;
      eventSource.endSec = playbackEndSec;
    }
    events.push({
      ordinal,
      stepIndex: gestureEvent.stepIndex,
      gridStep: Number.isFinite(gestureEvent.gridStep)
        ? gestureEvent.gridStep : gestureEvent.stepIndex,
      outStartSec: gestureEvent.startSec,
      outEndSec: gestureEvent.startSec + outputDuration,
      source: eventSource,
      gesture: {
        id: gesture.id,
        label: gesture.label,
        channel: gesture.channel,
        eventRef: { ...gestureEvent.eventRef },
        note: gestureEvent.rootNote,
        writtenNote: Number.isFinite(gestureEvent.writtenNote) ? gestureEvent.writtenNote : gestureEvent.rootNote,
        heardNotes: Array.isArray(gestureEvent.heardNotes) ? gestureEvent.heardNotes.slice() : [gestureEvent.rootNote],
        velocity: gestureEvent.velocity,
        gate: gestureEvent.gate,
        durationSec: gestureEvent.durationSec,
        nudge: Number.isFinite(gestureEvent.nudge) ? gestureEvent.nudge : 0,
        rawStartSec: Number.isFinite(gestureEvent.rawStartSec)
          ? gestureEvent.rawStartSec : gestureEvent.startSec,
      },
      transform: { kind: 'loom.bind', mapping, rate, semitones, voice: materialIndex + 1 },
      targets: { machineVoice: materialIndex + 1, studioNote: gestureEvent.rootNote, opzChannel: gesture.channel + 1 },
    });
  }

  const sourceName = clean[0].origin.sourceName;
  const sourceStart = Math.min(...clean.map((item) => item.origin.startSec));
  const sourceEnd = Math.max(...clean.map((item) => item.origin.endSec));
  const { events: ignoredGestureEvents, ...gestureMeta } = gesture;
  const plan = {
    schemaVersion: LOOM_SCHEMA_VERSION,
    compilerVersion: 'loom-v3',
    weaveNumber,
    mapping,
    source: {
      id: clean[0].origin.sourceId,
      sha256: /^sha256:[a-f0-9]{64}$/i.test(clean[0].origin.sourceId)
        ? clean[0].origin.sourceId : null,
      name: sourceName,
      size: clean[0].origin.sourceSize,
      startSec: sourceStart,
      endSec: sourceEnd,
    },
    materialLabel: clean.map((item) => item.label).join(' ').slice(0, 80),
    materials: clean,
    gesture: {
      ...gestureMeta,
      id: gesture.id,
      kind: gestureKind,
      label: gesture.label,
      channel: gesture.channel,
      bpm: gesture.bpm,
      swing: gesture.swing,
      bars: gesture.bars || 1,
      eventCount: score.length,
    },
    referenceNote,
    events,
    durationSec: Math.max(...events.map((event) => event.outEndSec)),
    diagnostics: { eventCount: events.length, materialCount: clean.length, tracedCount: events.length },
  };
  return reidentifyLoomPlan(plan);
}

export function traceLoomEvent(plan, eventId) {
  if (!plan || !Array.isArray(plan.events)) return null;
  return plan.events.find((event) => event.id === eventId) || null;
}

export function sourceMatchesPlan(plan, { id = null, hash = null, name = null, size = null } = {}) {
  if (!plan || !plan.source) return false;
  const validHash = (value) => /^sha256:[a-f0-9]{64}$/i.test(String(value || ''))
    ? String(value).toLowerCase() : null;
  const expected = validHash(plan.source.sha256) || validHash(plan.source.id);
  const actual = validHash(hash) || validHash(id);
  // Filename/size-only legacy plans remain fully inspectable, but can never be
  // considered online or enter an audio print without cryptographic identity.
  return !!expected && !!actual && expected === actual;
}
